# Generated by Django 4.0.5 on 2022-06-20 13:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('occupants', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wakonizone.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wakonizone.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('business_email', models.EmailField(max_length=30)),
                ('business_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('link', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wakonizone.locality')),
            ],
        ),
    ]
