# Generated by Django 4.0.5 on 2022-06-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakonizone', '0003_business_owner_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='locality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
