# Generated by Django 4.0.5 on 2022-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakonizone', '0009_business_description_business_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
